[terminal]
  shell = { program = "/bin/zsh", args = ["--login"] }

[env]
  TERM = "xterm-256color"

[window]
  opacity = 0.95
  dynamic_title = true
  decorations = "Buttonless"
  startup_mode = "Windowed"
  dimensions = { columns = 200, lines = 50 }

[scrolling]
  history = 50000

[font]
  normal = { family = "0xProto", style = "Regular" }
  bold = { family = "0xProto", style = "Bold" }

[cursor]
  style = { shape = "Block", blinking = "Off" }
  thickness = 0.15

# Colors (Tokyo Night Storm)
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"

[colors.hints]
    start = { foreground = "#908caa", background = "#1f1d2e" }
    end = { foreground = "#6e6a86", background = "#1f1d2e" }

[keyboard]
  bindings = [
    { key = "K", mods = "Command", mode = "~Vi|~Search", chars = "x0c" },
    { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ClearHistory" },
    { key = "Key0", mods = "Command", action = "ResetFontSize" },
    { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
    { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    { key = "NumpadAdd", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    { key = "NumpadSubtract", mods = "Command", action = "DecreaseFontSize" },
    { key = "V", mods = "Command", action = "Paste" },
    { key = "C", mods = "Command", action = "Copy" },
    { key = "C", mods = "Command", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "H", mods = "Command", action = "Hide" },
    { key = "H", mods = "Command|Alt", action = "HideOtherApplications" },
    { key = "M", mods = "Command", action = "Minimize" },
    { key = "Q", mods = "Command", action = "Quit" },
    { key = "W", mods = "Command", action = "Quit" },
    { key = "N", mods = "Command", action = "SpawnNewInstance" },
    { key = "F", mods = "Command|Control", action = "ToggleFullscreen" },
    { key = "F", mods = "Command", mode = "~Search", action = "SearchForward" },
    { key = "B", mods = "Command", mode = "~Search", action = "SearchBackward" }
  ]
